name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release-binaries:
    name: Release binaries
    runs-on: ubuntu-22.04
    # strategy:
    #   matrix:
    #     goos: [linux, darwin]
    #     goarch: ['386', amd64, arm64]
    #     exclude:
    #       - goarch: '386'
    #         goos: darwin
    steps:
      - uses: actions/checkout@v3
      - id: go-version
        run: echo "version=$(cat ./.go-version)" >> $GITHUB_OUTPUT
      - name: Release binary
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GO_CI }}
